name: Update Open Source Contributions
on:
  schedule:
    - cron: "0 0 * * *"  # update everyday
  workflow_dispatch:      # run manually allowed

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-contributions@v2
        with:
          username: AndersonTsaiTW
          max_repos: 5
          readme_path: README.md
          commit_message: "chore: update contributed repositories list"
